const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// the Schema defines the structure of our documents(blogs)

// the first param for the Schema constructor will be the format of the object (fields, etc)
// the second param is a 'options' param which specifies any certain behaviours we want
//      in this case we have autogenerated timestamp properties for our blog objects
//      in the future when we update/create/delete in the future, the timestamp properties are there
const blogSchema = Schema({
    title: {
        type: String,
        required: true,
      },
      snippet: {
        type: String,
        required: true,
      },
      body: {
        type: String,
        required: true
      }
}, { timestamps: true });

// the model wraps a Schema and provides us with an interface to communicate
//      with a DB collection with documents of the Schema type:

const Blog = mongoose.model('Blog', blogSchema)

// recall the module export functionality, we'll use this to 
//      distribute our Blog model throughout our project:
module.exports = Blog;

